### ISSUE TITLE
Base Graph

### ISSUE THREAD

**Issue by alino20** [ZacharyChenpk/EGT2#1]
Hi, I'm trying to run your model and build it for Farsi language. Can you tell me which steps of the Hosseini ACL2019 [repository](https://github.com/mjhosseini/linkpred_entgraph) do I need to go through to build the local triples and base graphs?

Thanks in advance

**Comment by ZacharyChenpk** [comment]
Hello!
If my memory serves me right, you should run the following steps in Hosseini ACL2019 repo:

- Cloning the project and installing the requirements
- Preparing the data
- Training the link prediction model
- Computing triple (link) probabilities for seen and unseen triples
- Building the entailment graphs
While "Building the entailment graphs", use the following command to build the base graphs "on all triples":
`python randWalk/randWalkMatFactory.py --probs_file_path NS_probs_all.txt --triples_path convE/data/NS/all.txt --max_new_args 50 --entgraph_path typedEntGrDir_NS_all_AUG_MC
`
If come into any problem, let me know it plz. Thanks!

**Comment by alino20** [comment]
Hello again!

Thank you for the quick and helpful answer. But now I have another question.

I followed the steps in Hosseini ACL2019 repo and now I have a `typedEntGrDir_NS_all_AUG_MC` directory.
But I don't see a `ent` directory. What is supposed to be in it and how can I get it?

Thanks again!

**Comment by ZacharyChenpk** [comment]
Oh, I found that maybe downloading evaluation repository (https://github.com/mjhosseini/entgraph_eval) will generate `ent` directory in `gfiles`.
That might be a mistake in README waiting for fixing, and you can execute step 2 before step 1.
Thank you for your feedback!
